library(GSVA)
data<-read.table("d:/Mergedata_counts_NOREP_morethanequalto5.txt",sep = "\t",header = TRUE,row.names = 1)
rownames(data)<-toupper(rownames(data))
genset<-read.table("c:/Users/xjmik/Downloads/c2.cp.kegg.v2023.1.Hs.symbols_NEW.txt",sep = "\t",header = TRUE)
genset<-as.list(genset)
gsva<-gsva(expr = as.matrix(data),gset.idx.list = genset,kcdf="Poisson",parallel.sz=20)
gsva2<-gsva(expr = as.matrix(data),gset.idx.list = genset,method="ssgsea",parallel.sz=20)
write.table(gsva,file = "gsva.txt",sep = "\t")
write.table(gsva2,file = "gsva2.txt",sep = "\t")
h<-read.table("C:/Users/xjmik/Downloads/msigdb.v2023.1.Hs.symbols.txt",sep = "\t")
rownames(h)<-h$V1
h<-as.data.frame(t(h))
h<-h[-1,]
h<-h[-1,]
h<-as.list(h)
gsva3<-gsva(expr = as.matrix(data),gset.idx.list = h,kcdf="Poisson",parallel.sz=20)
gsva4<-gsva(expr = as.matrix(data),gset.idx.list = h,method="ssgsea",parallel.sz=20)
write.table(gsva3,file = "gsva3.txt",sep = "\t")
write.table(gsva4,file = "gsva4.txt",sep = "\t")
data2<-read.table("d:/Mergedata_counts_NOREP_morethanequalto5_human.txt",sep = "\t",header = TRUE,row.names = 1)
gsva5<-gsva(expr = as.matrix(data2),gset.idx.list = h,kcdf="Poisson",parallel.sz=20)
gsva6<-gsva(expr = as.matrix(data2),gset.idx.list = h,method="ssgsea",parallel.sz=20)
write.table(gsva5,file = "gsva5.txt",sep = "\t")
write.table(gsva6,file = "gsva6.txt",sep = "\t")
